project:
  type: book

book:
  title: "Analyzing Ecological Networks"
  
  author: 
    - name: "Sonia Kefi"
      orcid: "0000-0002-9678-7770"
      url: "http://sonia.kefi.fr"
      affiliations: 
        - name: CNRS
          url: "https://isem-evolution.fr/"
    - name: "Sophie Donnet"
      orcid: "0000-0003-4370-7316"
      url: "https://sophiedonnet.github.io/"
      affiliations: 
        - name: INRAE
          url: "https://www.inrae.fr/"
    - name: "Camille Coux"
      orcid: "0000-0002-6346-9194"
      url: "https://www.fondationbiodiversite.fr/en/membre/camille-coux/"
      affiliations: 
        - name: FRB-CESAB
          url: "https://www.fondationbiodiversite.fr/en/about-the-foundation/le-cesab/"
      
  date: today
  description:  |
    FRB-CESAB & ANR ECONET course
    <br /><br />
    <a href="https://www.fondationbiodiversite.fr/en/evenement/frb-cesab-analyzing-ecological-network-data-2024/">
      <img class="logo" src="images/banner-networks_150dpi.png" style="width: 100%;" />
    </a>

  favicon: images/logo-networks_150dpi.png
  
  page-footer: 
    left: "&copy; CC-By [FRB-CESAB](https://www.fondationbiodiversite.fr/en/about-the-foundation/le-cesab/)"
    center: "Code source available on [{{< fa brands github >}}](https://github.com/econetoolbox/econetoolbox.github.io/)"
    right: "Built with [Quarto](https://quarto.org/)"
    border: true
  
  reader-mode: false
  search: false
  
  chapters:
    - index.qmd
    - part: "PREREQUISITES"
      chapters: 
        - chapters/setting-up-r.qmd
        - chapters/install-packages.qmd
    - part: "COURSES"
      chapters: 
        - chapters/day1_intro.qmd
        - chapters/day1_what-eco-net.qmd
        - chapters/day1_what-eco-net2.qmd
        - chapters/day1_why-net.qmd
        - chapters/day2_metrics.qmd
        - chapters/day2_complex-stab.qmd
        - chapters/day2_eco-net-structure.qmd
        - chapters/day3_sbm.qmd
        - chapters/day4_multilayer.qmd
        - chapters/day4_multilevel.qmd
        - chapters/day5_collection.qmd
        - chapters/day5_motifs.qmd
    - part: "EXERCISES"
      chapters:
        - text: (d1) igraph exercise
          href: chapters/day1_0_igraph.html
        - text: (d1) graph exploration
          href: chapters/day1_1_Graph_Exploration.html
        - text: (d2) network structure
          href: chapters/day2.html
        - text: (d3) SBM
          href: chapters/TutorialBM.qmd
#        - chapters/TutorialBM.qmd
        - text: (d4) multilevel
          href: chapters/TutorialDattilo.qmd
#        - chapters/TutorialDattilo.qmd



    
format:
  html: 
    theme: [cosmo, css/styles.css]
    code-copy: true
    code-line-numbers: false
